#Placeholders available: 

#{NAME} - Le nom du Joueurs
#{UUID} - L'UUID du Joueurs
#{REASON} - La raison pour kick / ban / mute
#{REMAININGTIME} - Le temps restant d'un ban / mute, utilisant le format temps spécifié plus bas
#{BY} - Le nom de la personne ayant kick / ban ou mutes
#{DETAILS} - Si un message à un détails il faut utiliser celui si.
#{BANAT} - Pour la date d'un ban.
#{MUTEAT} - Pour la date d'un mute.
#{DATE} - Pour la date de quelque chose.

mysql:
  host: 'localhost'
  port: 3306
  username: 'bungeeUtils'
  password: 'secret'
  database: 'bungeeUtils'

lang:

  prefix: '&6&l[&r&2Pump&eMy&aStaff&6&l]&r'
  console_prefix: '[PumpMyStaff] '
  time_format: '{DAYS} jours(s), {HOURS} heure(s), {MINUTES} min(s) et {SECONDS} sec(s)'
  time_format_permanent: 'PERMANENT'

  errors:
    no_permissions: '&cVous n avez pas la permission.'
    player_not_found: '&cCe joueur est introuvable.'
    player_not_online: '&cThe player &e{NAME} &cis not online.'
    internal_error: '&c INTERNAL SERVER ERROR: &e{DETAILS}'
    player_already_banned: '&cLe joueur &e{NAME} &cest deja banni.'
    player_not_banned: '&cLe joueur &e{NAME} &cn est pas banni.'
    player_already_muted: '&cLe joueur est deja mute.'
    player_not_muted: '&cLe joueur &e{NAME} &cn est pas mute.'
    unknown_timeunit: '&cErreur TimeUnit referer vous à vos superieurs.'

  banmessage:
  - '&cVous avez ete banni du serveur.'
  - '&cRaison: &e{REASON}'
  - '&cBanni par: &e{BY}'
  - '&cTemps restant: &e{REMAININGTIME}'

  mutemessage:
  - '&cVous etes mute du serveur.'
  - '&cRaison: &e{REASON}'
  - '&cMute par: &e{BY}'
  - '&cTemps restant: &e{REMAININGTIME}'

  pastbanmessage:
  - '&cAnciens bannissement'
  - '&cRaison : &e{REASON}'
  - '&cBanni par : &e{BY}'

  pastmutemessage:
  - '&cAnciens Mute'
  - '&cRaison : &e{REASON}'
  - '&cMute par : &e{BY}'

  kickmessage:
  - '&cVous avez ete kick du serveur par &e{NAME}.'
  - '&cRaison: &e{REASON}'

  warnmessage:
  - '&cVous avez ete warn par &e{NAME}.'
  - '&cRaison : &e{REASON}'

  commands:
    warn:
      succes: '&cVous avez warn &e{NAME}.'
      syntax: '&cUtilisation /warn <Joueur> <Raison>'
    ban:
      syntax: '&cUtilisation: &c/ban <Joueurs> <Temps> <TimeUnit> <Raison>'
      banned: '&aVous avez banni &e{NAME}&a avec succes.'
      broadcast:
      - '&e{NAME} &ca ete banni par &e{BY}&c.'
      - '&cRaison: &e{REASON}'
      - '&cTemps: &e{REMAININGTIME}'
    unban:
      syntax: '&cUsage: &c/unban <Joueurs>'
      unbanned: '&aVous avez unban &e{NAME}&a avec succes.'
      broadcast:
      - '&e{NAME} &ca ete debanni par &e{BY}&c.'
    mute:
      syntax: '&cUtilisation: &c/mute <Joueurs> <Time> <TimeUnit> <Raison>'
      muted: '&aVous avez mute &e{NAME}&a avec succes.'
      broadcast:
      - '&e{NAME} &ca ete mute par &e{BY}&c.'
      - '&cRaison: &e{REASON}'
      - '&cTemps: &e{REMAININGTIME}'
    unmute:
      syntax: '&cUtilisation: /unmute <Joueurs>'
      unmuted: '&aVous avez demute &e{NAME}&a avec succes.'
      broadcast:
      - '&e{NAME} &ca ete demute par &e{BY}&c.'
    kick:
      syntax: '&cUtilisation: &c/kick <Joueurs> <Reason>'
      kicked: '&aVous avez kick &e{NAME}&a avec succes.'
      broadcast:
      - '&e{NAME} &ca ete kick par &e{BY}&c.'
      - '&cRaison: &e{REASON}'
    history:
      succes: '&4Historique des sanction de &e{NAME}'
      no_ban: '&aAucun ancien ban'
      no_mute: '&aAucun ancien mute'
    check:
      succes: '&cInformation pour le joueurs &e{NAME}'
      syntax: '&cUtilisation: $c/check <joueur>'
      banned:
        true:
          - '&cLe joueur &e{NAME} &cest &4&lBANNIE&c.'
          - '&cRaison: &e{REASON}'
          - '&cBanni par: &e{BY}'
          - '&cTemps restant: &e{REMAININGTIME}'
        false:
          - '&fLe joueur &e{NAME} &fest pas bannie.'
      muted:
        true:
          - '&cLe joueur &e{NAME} &cest &4&lMUTE&c.'
          - '&cRaison: &e{REASON}'
          - '&cMute par: &e{BY}'
          - '&cTemps restant: &e{REMAININGTIME}'
        false:
          - '&fLe joueur &e{NAME} &fest pas mute.'
      warn:
        true:
          - '&c-------&eListe des warn&c-------'
          - '&cAverti par &e{NAME}'
          - '&cAverti pour &e{REASON}'
          - '&cAverti le &e{DATE}'
        false:
          - '&fLe joueur $e{NAME} est pas Warn'
        


