name: PMK-BungeeStaff
main: fr.pmk_bungee.Main
version: 1.0
author: Sufike

commands:
  gunban: 
    description: Commande d'unban
    permission: bungeestaff.command.unban
    
  gunmute: 
    description:  Commande de unmute
    permission: bungeestaff.command.unmute 
  
  gmute:  
    description:  Commande de mute
    permission: bungeestaff.command.mute 
  
  gban: 
    description: Commande de ban
    permission: bungeestaff.command.ban
    
  ghistory: 
    description: commande d'historique de sanction
    permission: bungeestaff.command.history
    
  ginfo: 
    description: commande d'info sur un joueurs
    permission: bungeestaff.command.information
    
  gkick: 
    description: commande de kick
    permission: bungeestaff.command.kick
  
  gwarn: 
    description: commande de warn
    permission: bungeestaff.command.warn 

  gcheck:
    description: commande de check du joueurs
    permission: bungeestaff.command.check